import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Navbar = [
  {
    name: "LLM",
    link: "/llm",
  },
  {
    name: "AI Agents",
    link: "/agents",
  },
  {
    name: "Docs",
    link: "/docs",
  },
]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <section>
      <header className="flex px-5 py-3 bg-slate-800 justify-between items-center">
        <div className="flex justify-between items-center">
          <div>
            <Image src='' alt="img"/>
          </div>
          <div>logo text</div>
        
        </div>
        <div className="flex justify-between gap-x-2 items-center">
          <div className="flex justify-between gap-x-5 items-center">
            {
              Navbar.map((item, index) => (
                <Link href={item.link} key={index}>
                  {item.name}
                </Link>
              ))
            }
          </div>
          <div className=" cursor-pointer">
            info
          </div>
          <div className=" cursor-pointer">
            user
          </div>
        </div>
      </header>
      <div>{children}</div>
      </section>
      </body>
    </html>
  );
}
